export const fakeData = [
  {
    id: "1",
    customerName: "John",
    phone: "9912456721",
    email: "john.doe@example.com",
    companyName:"ABC"
  },
  {
    id: "2",
    customerName: "Jane",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "3",
    customerName: "Tom",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "4",
    customerName: "Ram",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "5",
    customerName: "Sam",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "1",
    customerName: "John",
    phone: "9912456721",
    email: "john.doe@example.com",
  },
  {
    id: "2",
    customerName: "Jane",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "3",
    customerName: "Tom",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "4",
    customerName: "Ram",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "5",
    customerName: "Sam",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "1",
    customerName: "John",
    phone: "9912456721",
    email: "john.doe@example.com",
  },
  {
    id: "2",
    customerName: "Jane",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "3",
    customerName: "Tom",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "4",
    customerName: "Ram",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "5",
    customerName: "Sam",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
   {
    id: "1",
    customerName: "John",
    phone: "9912456721",
    email: "john.doe@example.com",
  },
  {
    id: "2",
    customerName: "Jane",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "3",
    customerName: "Tom",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "4",
    customerName: "Ram",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },
  {
    id: "5",
    customerName: "Sam",
    phone: "9912456721",
    email: "jane.doe@example.com",
    state: "NY",
  },

];

export const itemData = [
  {
    id: "1",
    item_name: "Item",
    hsn_san: "123456",
    part_number: "1234567890",
    mrp: "123",
  },
];
